### ISSUE TITLE
Why mount the '.:/var/www' in docker-compose file?

### ISSUE THREAD

**Issue by Evilran** [ytake/hack-pds-skeleton#4]
Excuse me, I have a question about the `docker-compose.yml` file.

Why the code here:
```
volumes:
      - .:/var/www
```

I think we should mount `./src` to `/var/www` here and specify the `index.hack` in `./src/public`, shall I?

**Comment by ytake** [comment]
for example [ytake/nazg-skeleton](https://github.com/ytake/nazg-skeleton)

**Comment by Evilran** [comment]
But in the file `docker/hhvm/php.ini`, it seems that already defined `hhvm.server.source_root = /var/www/public`. If I mount `.` to `/var/www` in docker-compose file, I've got 404 File Not Found error, and after that I tried to mount `./src` to` /var/www` and created the `index.hack` file in `./src/public`, It works.
